[[headers]]
  for = "/*"

    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Expose-Headers = "*"
      Cross-Origin-Resource-Policy = "cross-origin"
      Content-Security-Policy = "default-src 'self' *; frame-ancestors 'self'; form-action 'self'"
      script-src '*';